spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/jewel/**



       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
           - Path=/order/**


 application:
   name: API-GATEWAY


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/